import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useUser } from '@auth0/nextjs-auth0';
import Link from 'next/link';


export default function Home() {
    const { user, error, isLoading } = useUser();

    if (isLoading) return <div>Loading...</div>;
    if (error) return <div>{error.message}</div>;

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <nav>
                    <ul>
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <Link href="/profile-ssr">Profile SSR</Link>
                        </li>
                        <li>
                            <Link href="/profile-csr">Profile CSR</Link>
                        </li>
                        <li>
                            <Link href="/test-api">Test API</Link>
                        </li>
                    </ul>
                </nav>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>
                {user ? (
                    <div>
                        Welcome {user.name}!{' '}
                        <a href="/api/auth/logout">Logout</a>
                        <pre>{JSON.stringify(user, null, 2)}</pre>
                    </div>
                ) : (
                    <a href="/api/auth/login">Login</a>
                )}
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
